/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordCounterRouteImport } from './routes/word-counter'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as LoremIpsumGeneratorRouteImport } from './routes/lorem-ipsum-generator'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as ImageToBase64RouteImport } from './routes/image-to-base64'
import { Route as ImageFormatConverterRouteImport } from './routes/image-format-converter'
import { Route as ImageCropperRouteImport } from './routes/image-cropper'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as DiffCheckerRouteImport } from './routes/diff-checker'
import { Route as CsvXlsxConverterRouteImport } from './routes/csv-xlsx-converter'
import { Route as IndexRouteImport } from './routes/index'

const WordCounterRoute = WordCounterRouteImport.update({
  id: '/word-counter',
  path: '/word-counter',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const LoremIpsumGeneratorRoute = LoremIpsumGeneratorRouteImport.update({
  id: '/lorem-ipsum-generator',
  path: '/lorem-ipsum-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToBase64Route = ImageToBase64RouteImport.update({
  id: '/image-to-base64',
  path: '/image-to-base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageFormatConverterRoute = ImageFormatConverterRouteImport.update({
  id: '/image-format-converter',
  path: '/image-format-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCropperRoute = ImageCropperRouteImport.update({
  id: '/image-cropper',
  path: '/image-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const DiffCheckerRoute = DiffCheckerRouteImport.update({
  id: '/diff-checker',
  path: '/diff-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const CsvXlsxConverterRoute = CsvXlsxConverterRouteImport.update({
  id: '/csv-xlsx-converter',
  path: '/csv-xlsx-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/csv-xlsx-converter': typeof CsvXlsxConverterRoute
  '/diff-checker': typeof DiffCheckerRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-cropper': typeof ImageCropperRoute
  '/image-format-converter': typeof ImageFormatConverterRoute
  '/image-to-base64': typeof ImageToBase64Route
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/lorem-ipsum-generator': typeof LoremIpsumGeneratorRoute
  '/tools': typeof ToolsRoute
  '/word-counter': typeof WordCounterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/csv-xlsx-converter': typeof CsvXlsxConverterRoute
  '/diff-checker': typeof DiffCheckerRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-cropper': typeof ImageCropperRoute
  '/image-format-converter': typeof ImageFormatConverterRoute
  '/image-to-base64': typeof ImageToBase64Route
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/lorem-ipsum-generator': typeof LoremIpsumGeneratorRoute
  '/tools': typeof ToolsRoute
  '/word-counter': typeof WordCounterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/csv-xlsx-converter': typeof CsvXlsxConverterRoute
  '/diff-checker': typeof DiffCheckerRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-cropper': typeof ImageCropperRoute
  '/image-format-converter': typeof ImageFormatConverterRoute
  '/image-to-base64': typeof ImageToBase64Route
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
  '/lorem-ipsum-generator': typeof LoremIpsumGeneratorRoute
  '/tools': typeof ToolsRoute
  '/word-counter': typeof WordCounterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/csv-xlsx-converter'
    | '/diff-checker'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-format-converter'
    | '/image-to-base64'
    | '/image-to-pdf'
    | '/json-formatter'
    | '/lorem-ipsum-generator'
    | '/tools'
    | '/word-counter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/csv-xlsx-converter'
    | '/diff-checker'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-format-converter'
    | '/image-to-base64'
    | '/image-to-pdf'
    | '/json-formatter'
    | '/lorem-ipsum-generator'
    | '/tools'
    | '/word-counter'
  id:
    | '__root__'
    | '/'
    | '/csv-xlsx-converter'
    | '/diff-checker'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-format-converter'
    | '/image-to-base64'
    | '/image-to-pdf'
    | '/json-formatter'
    | '/lorem-ipsum-generator'
    | '/tools'
    | '/word-counter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CsvXlsxConverterRoute: typeof CsvXlsxConverterRoute
  DiffCheckerRoute: typeof DiffCheckerRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  ImageCropperRoute: typeof ImageCropperRoute
  ImageFormatConverterRoute: typeof ImageFormatConverterRoute
  ImageToBase64Route: typeof ImageToBase64Route
  ImageToPdfRoute: typeof ImageToPdfRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
  LoremIpsumGeneratorRoute: typeof LoremIpsumGeneratorRoute
  ToolsRoute: typeof ToolsRoute
  WordCounterRoute: typeof WordCounterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word-counter': {
      id: '/word-counter'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof WordCounterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lorem-ipsum-generator': {
      id: '/lorem-ipsum-generator'
      path: '/lorem-ipsum-generator'
      fullPath: '/lorem-ipsum-generator'
      preLoaderRoute: typeof LoremIpsumGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-base64': {
      id: '/image-to-base64'
      path: '/image-to-base64'
      fullPath: '/image-to-base64'
      preLoaderRoute: typeof ImageToBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-format-converter': {
      id: '/image-format-converter'
      path: '/image-format-converter'
      fullPath: '/image-format-converter'
      preLoaderRoute: typeof ImageFormatConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-cropper': {
      id: '/image-cropper'
      path: '/image-cropper'
      fullPath: '/image-cropper'
      preLoaderRoute: typeof ImageCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diff-checker': {
      id: '/diff-checker'
      path: '/diff-checker'
      fullPath: '/diff-checker'
      preLoaderRoute: typeof DiffCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csv-xlsx-converter': {
      id: '/csv-xlsx-converter'
      path: '/csv-xlsx-converter'
      fullPath: '/csv-xlsx-converter'
      preLoaderRoute: typeof CsvXlsxConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CsvXlsxConverterRoute: CsvXlsxConverterRoute,
  DiffCheckerRoute: DiffCheckerRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  ImageCropperRoute: ImageCropperRoute,
  ImageFormatConverterRoute: ImageFormatConverterRoute,
  ImageToBase64Route: ImageToBase64Route,
  ImageToPdfRoute: ImageToPdfRoute,
  JsonFormatterRoute: JsonFormatterRoute,
  LoremIpsumGeneratorRoute: LoremIpsumGeneratorRoute,
  ToolsRoute: ToolsRoute,
  WordCounterRoute: WordCounterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
