import { createFileRoute } from "@tanstack/react-router";
import { useState, useMemo, useCallback } from "react";
import { IconTypography, IconCopy, IconTrash, IconCheck, IconRefresh, IconBolt, IconLock, IconSearch } from "@tabler/icons-react";

import ToolInfo from "@/components/ToolInfo";
import RelatedTools from "@/components/RelatedTools";
import { getSeoMetadata } from "@/lib/seo";

const LOREM_WORDS = [
    "lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipiscing",
    "elit",
    "sed",
    "do",
    "eiusmod",
    "tempor",
    "incididunt",
    "ut",
    "labore",
    "et",
    "dolore",
    "magna",
    "aliqua",
    "ut",
    "enim",
    "ad",
    "minim",
    "veniam",
    "quis",
    "nostrud",
    "exercitation",
    "ullamco",
    "laboris",
    "nisi",
    "ut",
    "aliquip",
    "ex",
    "ea",
    "commodo",
    "consequat",
    "duis",
    "aute",
    "irure",
    "dolor",
    "in",
    "reprehenderit",
    "in",
    "voluptate",
    "velit",
    "esse",
    "cillum",
    "dolore",
    "eu",
    "fugiat",
    "nulla",
    "pariatur",
    "excepteur",
    "sint",
    "occaecat",
    "cupidatat",
    "non",
    "proident",
    "sunt",
    "in",
    "culpa",
    "qui",
    "officia",
    "deserunt",
    "mollit",
    "anim",
    "id",
    "est",
    "laborum",
];

const faqs = [
    {
        question: "Is the generated Lorem Ipsum text random?",
        answer: "The text is generated by selecting random words from the classic Lorem Ipsum vocabulary. While it's not a direct copy of the original Cicero text, it mimics its structure to provide effective placeholder content.",
    },
    {
        question: "Can I use this text for commercial projects?",
        answer: "Yes, Lorem Ipsum is standard placeholder text used in the design and printing industry and is free to use for any purpose, including commercial projects.",
    },
    {
        question: "Is my data private when using this tool?",
        answer: "Absolutely. As with all SnapBit Tools, the generation happens entirely in your browser. No data is sent to any server.",
    },
    {
        question: "Does it support paragraph formatting?",
        answer: "Yes, you can generate text in words, sentences, or paragraphs, and the formatting is preserved when you copy it to your clipboard.",
    },
];

export const Route = createFileRoute("/lorem-ipsum-generator")({
    head: () =>
        getSeoMetadata({
            title: "Lorem Ipsum Generator | Random Placeholder Text | SnapBit Tools",
            description:
                "Generate custom Lorem Ipsum placeholder text for your designs and layouts. Choose paragraphs, words, or sentences. 100% private and fast.",
            keywords: ["lorem ipsum generator", "placeholder text", "dummy text", "random text", "developer tools"],
            url: "/lorem-ipsum-generator",
            type: "software",
            faqs,
        }),
    component: LoremIpsumComponent,
});

function LoremIpsumComponent() {
    const [count, setCount] = useState(3);
    const [type, setType] = useState<"paragraphs" | "sentences" | "words">("paragraphs");
    const [generatedText, setGeneratedText] = useState("");
    const [copySuccess, setCopySuccess] = useState(false);

    const generateWords = (num: number) => {
        let result = [];
        for (let i = 0; i < num; i++) {
            result.push(LOREM_WORDS[Math.floor(Math.random() * LOREM_WORDS.length)]);
        }
        return result.join(" ");
    };

    const generateSentences = (num: number) => {
        let result = [];
        for (let i = 0; i < num; i++) {
            let sentenceLen = Math.floor(Math.random() * 10) + 5;
            let sentence = generateWords(sentenceLen);
            sentence = sentence.charAt(0).toUpperCase() + sentence.slice(1) + ".";
            result.push(sentence);
        }
        return result.join(" ");
    };

    const generateParagraphs = (num: number) => {
        let result = [];
        for (let i = 0; i < num; i++) {
            let paraLen = Math.floor(Math.random() * 4) + 3;
            result.push(generateSentences(paraLen));
        }
        return result.join("\n\n");
    };

    const generateText = useCallback(() => {
        let text = "";
        const safeCount = Math.max(1, Math.min(count, 100)); // Limit to 100 for performance
        if (type === "words") text = generateWords(safeCount);
        else if (type === "sentences") text = generateSentences(safeCount);
        else text = generateParagraphs(safeCount);
        setGeneratedText(text);
    }, [count, type]);

    // Initial generation
    useMemo(() => {
        generateText();
    }, []);

    const copyToClipboard = useCallback(async () => {
        if (!generatedText) return;
        try {
            await navigator.clipboard.writeText(generatedText);
            setCopySuccess(true);
            setTimeout(() => setCopySuccess(false), 2000);
        } catch (err) {
            console.error("Failed to copy:", err);
        }
    }, [generatedText]);

    const clearText = () => {
        setGeneratedText("");
        setCount(1);
    };

    return (
        <div className="min-h-screen bg-gradient-to-br from-gray-800 to-slate-900 pt-24 pb-8 px-4 flex flex-col font-sans">
            <div className="text-center mb-8">
                <h1 className="text-3xl font-bold text-gray-100 mb-2">
                    Lorem <span className="text-brand-primary">Ipsum</span> Generator
                </h1>
                <p className="text-md text-gray-200">Instant placeholder text for your next big project.</p>
            </div>

            <div className="flex-1 max-w-6xl w-full mx-auto space-y-6">
                <div className="bg-gray-800 rounded-xl shadow-lg p-6 border border-gray-700">
                    <div className="flex flex-wrap items-center gap-6 justify-center lg:justify-between">
                        <div className="flex flex-wrap items-center gap-4">
                            <div className="flex flex-col">
                                <label className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Quantity</label>
                                <input
                                    type="number"
                                    min="1"
                                    max="100"
                                    value={count}
                                    onChange={(e) => setCount(parseInt(e.target.value) || 1)}
                                    className="w-24 px-3 py-2 bg-gray-700 border border-gray-600 rounded-lg text-gray-100 focus:outline-none focus:ring-2 focus:ring-brand-primary"
                                />
                            </div>

                            <div className="flex flex-col">
                                <label className="text-xs font-semibold text-gray-400 uppercase tracking-wider mb-2">Type</label>
                                <div className="flex p-1 bg-gray-900 rounded-lg">
                                    {(["paragraphs", "sentences", "words"] as const).map((t) => (
                                        <button
                                            key={t}
                                            onClick={() => setType(t)}
                                            className={`px-4 py-1.5 rounded-md text-sm font-medium transition-all ${
                                                type === t ? "bg-brand-primary text-white shadow-sm" : "text-gray-400 hover:text-gray-200"
                                            }`}
                                        >
                                            {t.charAt(0).toUpperCase() + t.slice(1)}
                                        </button>
                                    ))}
                                </div>
                            </div>
                        </div>

                        <div className="flex items-center gap-3">
                            <button
                                onClick={generateText}
                                className="inline-flex items-center gap-2 px-5 py-2.5 bg-gray-700 text-gray-100 rounded-lg hover:bg-gray-600 transition-colors duration-200 font-medium"
                            >
                                <IconRefresh className="w-5 h-5" />
                                <span>Regenerate</span>
                            </button>

                            <button
                                onClick={copyToClipboard}
                                disabled={!generatedText}
                                className={`inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-medium transition-all duration-200 disabled:opacity-50 disabled:cursor-not-allowed ${
                                    copySuccess ? "bg-green-800 text-green-200" : "bg-brand-primary text-white hover:bg-brand-hover"
                                }`}
                            >
                                {copySuccess ? (
                                    <>
                                        <IconCheck className="w-5 h-5" />
                                        <span>Copied!</span>
                                    </>
                                ) : (
                                    <>
                                        <IconCopy className="w-5 h-5" />
                                        <span>Copy All</span>
                                    </>
                                )}
                            </button>

                            <button
                                onClick={clearText}
                                className="p-2.5 text-red-400 hover:bg-red-400/10 rounded-lg transition-colors border border-transparent hover:border-red-400/20"
                                title="Clear"
                            >
                                <IconTrash className="w-5 h-5" />
                            </button>
                        </div>
                    </div>
                </div>

                <div className="bg-gray-800 rounded-xl shadow-lg p-8 border border-gray-700 min-h-[400px]">
                    {generatedText ? (
                        <div className="prose prose-invert max-w-none">
                            {generatedText.split("\n\n").map((para, i) => (
                                <p key={i} className="text-gray-200 text-lg leading-relaxed mb-6 last:mb-0">
                                    {para}
                                </p>
                            ))}
                        </div>
                    ) : (
                        <div className="h-full flex flex-col items-center justify-center text-gray-500 py-20">
                            <IconTypography className="w-16 h-16 opacity-10 mb-4" />
                            <p>Generate some magic text above...</p>
                        </div>
                    )}
                </div>

                <ToolInfo
                    title="Lorem Ipsum Generator"
                    description="A quick and easy way to generate standard dummy text for your mockups, websites, and design projects. Customize the output to fit your specific needs with options for paragraphs, sentences, and words."
                    features={[
                        {
                            title: "Custom Sizes",
                            description: "Generate exactly as much text as you need, from a single word to 100 paragraphs.",
                            icon: IconBolt,
                        },
                        {
                            title: "Smart Formatting",
                            description: "Sentences are properly capitalized and punctuated, and paragraphs are spaced correctly.",
                            icon: IconSearch,
                        },
                        {
                            title: "Privacy First",
                            description: "The generation logic runs entirely in your browser. No cookies, no tracking, no server calls.",
                            icon: IconLock,
                        },
                    ]}
                    steps={[
                        {
                            title: "Select Quantity",
                            description: "Choose how many items you want to generate (up to 100).",
                        },
                        {
                            title: "Choose Type",
                            description: "Pick between paragraphs, sentences, or individual words.",
                        },
                        {
                            title: "Copy & Use",
                            description: "Preview the text and use the Copy All button to take it to your project.",
                        },
                        {
                            title: "Regenerate",
                            description: "Want something different? Click regenerate to create a new set of random words.",
                        },
                    ]}
                    faqs={faqs}
                />
            </div>

            <RelatedTools currentToolSlug="lorem-ipsum-generator" category="Data" />
        </div>
    );
}
